# Server
server.port=8080

# MySQL DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=
#jdbc:mysql://localhost:3306/unireg_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=YOUR PASSWORD
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Schema initialization (seed data)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Jackson - serialize dates as ISO strings
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT Secret (256-bit / 32+ chars)
app.jwt.secret=UniRegSuperSecretKeyForJwtTokenSigning2026!
app.jwt.expiration=86400000
